services:
  - type: web
    name: airsign-asl-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: PORT
        value: 8000
      # ROBOFLOW_API_KEY will be set manually in Render dashboard for security
    healthCheckPath: /health
